//
//  RDPStrings.h
//  SpearnintIOS
//
//  Created by McElwain, Cori on 7/22/14.
//  Copyright (c) 2014 Spearmint. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "RDPConfig.h"

typedef enum {
    sPressAndHoldOnly,
    sPressAndHOldTheScreen, 
    sPressAndHold,
    sSettings,
    sUndoSavingBodyMessage,
    sUndoSavingUndoButton,
    sUndoSavingCancelButton,
    sSubmitFeedbackAlertText,
    sSubmitFeedbackAlertDismissButton,
    sBack,
    sNext, 
    sMyGoal,
    sNotificationSettings,
    sSubmitFeedback,
    sHistory,
    sToday,
    sYesterday,
    sMonday,
    sTuesday,
    sWednesday,
    sThursday,
    sFriday,
    sSaturday,
    sSunday,
    sLastWeek,
    sTwoWeeksAgo,
    sThreeWeeksAgo,
    sLastMonth,
    sJanuary,
    sFebruary,
    sMarch,
    sApril,
    sMay,
    sJune,
    sJuly,
    sAugust,
    sSeptember,
    sOctober,
    sNovember,
    sDecember,
    sLastYear,
    sOlder,
    sRateTheApp,
    sLogout,
    sJustKept,
    sGoal,
    sAmount,
    sAmountSaved,
    sIWantTo,
    sDaily,
    sWeeklyReport,
    sWeekly,
    sWhenIReachMyGoal,
    sWhenIDontSaveForThreeDays,
    sEmail,
    sPushNotifications,
    sFeedback,
    sTypeFeedbackHere,
    sUndo,
    sSubmit,
    sSlogan,
    sCoffeeExampleHeader,
    sCoffeeTapAndHold,
    sCoffeeCounterLabel,
    sCoffeeReleaseScreen,
    sAddToGoalInstructions,
    sContinue,
    sLogin,
    SEmailPlaceholder,
    sPasswordPlaceholder,
    sEmailValidation,
    sPasswordValidation,
    sKeepHolding,
    sKeepHolding3,
    sKeepHolding8,
    sBusExmapleHeader,
    sBusTapAndHold,
    sBusCounterLabel,
    sBusReleaseScreen,
    sUseKeepInstructions,
    sSetAGoal,
    sGoalAmount,
    sIwant,
    sWillCost,
    sVacation,
    sDebt,
    sRainy,
    sComputer,
    sWeekend,
    sSchool,
    sReleaseMessage1, 
    sReleaseMessage2,
    sGoalCaps,
    sKeptCaps,
    sSavedBy,
    sSaveSome,
    sRecord,
    sLoading,
    sReachedGoalLine1,
    sReachedGoalLine2,
    sReachedGoalButtonText,
    sMyProgressNullState,
    sLoginUnauthorized,
    sLoginGeneralError,
    sSignupUsernameError,
    sSignupGeneralError,
    sTapRecord,
    sWelcomeTitle,
    sWelcomeMessage,
    sNoNotifications,
    sYesNotifications,
    sSignUpToSave,
    sPrivacyPolicy,
    slegalLinks,
    sTermsOfService
} RDPStringID;

@interface RDPStrings : NSObject

+ (NSString *)stringForID:(RDPStringID)stringID;

@end
